name: Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.tag-version.outputs.new_version }}
      tag: ${{ steps.tag-version.outputs.new_tag }}
      changelog: ${{ steps.tag-version.outputs.changelog }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: 🏷️ Bump version and push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "minor"
          custom_release_rules: "feat:minor:✨ Features,fix:patch:🐛 Fixes,docs:patch:📰 Docs,chore:patch:🎨 Chore,pref:patch:🎈 Performance improvements,refactor:patch:🧹 Refactoring,build:patch:🔍 Build,ci:patch:🔍 CI,revert:patch:⏪ Revert,style:patch:🧹 Style,test:patch:👀 Test,release:major:📦 Release"

  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    needs: bump-version

    env:
      version: ${{ needs.bump-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: 🏗 Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .node-version

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        id: pnpm-install
        with:
          run_install: false
          package_json_file: package.json

      - name: 📂 Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 📂 Setup pnpm cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 👨🏻‍💻 Install dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-frozen-lockfile

      - name: 📝 Update package.json version
        run: |
          pnpm version ${{ env.version }} --no-git-tag-version

      - name: 🏗️ Run build
        run: |
          pnpm run build

      - name: Publish Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          body: ${{ needs.bump-version.outputs.changelog }}
          tag_name: ${{ needs.bump-version.outputs.tag }}
          target_commitish: ${{ github.sha }}
          files: dist/twitter-auto-spam-crawler.user.js